//go:build windows

package icon

import (
	_ "embed"
)

// Windows Shell_NotifyIcon (and therefore the getlantern/systray Windows
// backend) requires the icon bytes in ICO format. The two ICOs are
// generated by `scripts/gen-icon` (run via `make icons`) and committed
// to the repository so a fresh `go install` / cross-compile works
// without first running the generator.

//go:embed assets/icon-active.ico
var active []byte

//go:embed assets/icon-suspended.ico
var suspended []byte
