//go:build darwin

package icon

import (
	_ "embed"
)

// macOS NSStatusItem accepts PNG bytes directly. The two PNGs are
// generated by `scripts/gen-icon` (run via `make icons`) and committed
// to the repository so `go install github.com/nealhardesty/gwim@latest`
// works without first running the generator.

//go:embed assets/icon-active.png
var active []byte

//go:embed assets/icon-suspended.png
var suspended []byte
