# GWiM — Golang Window Manager
#
# This Makefile is the canonical interface for every dev workflow:
# build, test, run, package the .app bundle, manage versions, push releases.
# Per AGENTS.md it is the SINGLE supported way to commit and publish — never
# invoke git add/commit/push directly.
#
# Run `make help` for a categorised list of targets.

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BINARY        := gwim
PKG           := github.com/nealhardesty/gwim
CMD           := ./cmd/gwim
# BUILD_DIR intentionally != "build" to avoid conflicting with the phony
# `make build` target (would produce a "circular dependency dropped" warning).
BUILD_DIR     := dist
APP_NAME      := GWiM
APP_BUNDLE    := $(BUILD_DIR)/$(APP_NAME).app
APP_CONTENTS  := $(APP_BUNDLE)/Contents
APP_MACOS     := $(APP_CONTENTS)/MacOS
APP_RES       := $(APP_CONTENTS)/Resources
ICONSET_DIR   := assets/icon.iconset
ICNS          := $(BUILD_DIR)/icon.icns
PLIST_TPL     := assets/Info.plist.template

VERSION_FILE  := cmd/gwim/version.go
VERSION       := $(shell awk -F\" '/const Version/ {print $$2}' $(VERSION_FILE))

GO            := go
GOFLAGS       :=
LDFLAGS       := -s -w
BUILD_FLAGS   := -trimpath -ldflags "$(LDFLAGS)"

GREEN := \033[32m
BOLD  := \033[1m
RESET := \033[0m

.DEFAULT_GOAL := help

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------

.PHONY: help
help: ## Show this help message
	@printf "$(BOLD)GWiM Makefile — version $(VERSION)$(RESET)\n\n"
	@awk 'BEGIN {FS = ":.*?## "} \
		/^[a-zA-Z0-9_.-]+:.*?## / {printf "  $(GREEN)%-22s$(RESET) %s\n", $$1, $$2}' \
		$(MAKEFILE_LIST) | sort

# ---------------------------------------------------------------------------
# Build / run
# ---------------------------------------------------------------------------

# Files that go:embed depends on — must exist before any compile/vet/test
# step or the embed directive in internal/icon will fail. They're gitignored
# generated artifacts, regenerated by `scripts/gen-icon`.
EMBED_ICONS := internal/icon/assets/icon-active.png internal/icon/assets/icon-suspended.png

$(EMBED_ICONS): scripts/gen-icon/main.go
	@$(GO) run ./scripts/gen-icon

.PHONY: build
build: $(EMBED_ICONS) $(BUILD_DIR)/$(BINARY) ## Compile the gwim binary into ./dist

$(BUILD_DIR)/$(BINARY): $(EMBED_ICONS) $(shell find . -name '*.go' -not -path './$(BUILD_DIR)/*' -not -path './scripts/*') $(VERSION_FILE)
	@mkdir -p $(BUILD_DIR)
	@echo "==> Building $(BINARY) $(VERSION)"
	$(GO) build $(BUILD_FLAGS) -o $@ $(CMD)

.PHONY: run
run: build ## Build then launch the binary in the foreground (logs to stdout)
	$(BUILD_DIR)/$(BINARY)

.PHONY: run-app
run-app: app ## Build and launch the .app bundle (matches production layout)
	open -W $(APP_BUNDLE)

# ---------------------------------------------------------------------------
# Tests / quality
# ---------------------------------------------------------------------------

.PHONY: test
test: $(EMBED_ICONS) ## Run unit tests with the race detector
	$(GO) test -race ./...

.PHONY: test-short
test-short: $(EMBED_ICONS) ## Run unit tests without -race (CGO race-detection is slow)
	$(GO) test ./...

.PHONY: vet
vet: $(EMBED_ICONS) ## go vet across all packages
	$(GO) vet ./...

.PHONY: fmt
fmt: ## Format every Go file with gofmt
	$(GO) fmt ./...

.PHONY: tidy
tidy: ## Tidy go.mod / go.sum
	$(GO) mod tidy

.PHONY: lint
lint: vet ## Currently an alias for vet; extend with golangci-lint when adopted

.PHONY: check
check: fmt vet test ## Run fmt, vet, and tests — pre-commit gate

# ---------------------------------------------------------------------------
# Icon / app bundle
# ---------------------------------------------------------------------------

.PHONY: icons
icons: ## Regenerate menu-bar PNGs and the multi-resolution iconset
	$(GO) run ./scripts/gen-icon

# Mark the iconset directory as produced by `icons` so target dependencies
# resolve cleanly when `make app` is invoked from a clean checkout.
$(ICONSET_DIR)/icon_1024x1024.png: scripts/gen-icon/main.go
	@$(GO) run ./scripts/gen-icon

$(ICNS): $(ICONSET_DIR)/icon_1024x1024.png
	@mkdir -p $(BUILD_DIR)
	@echo "==> Converting iconset to icns"
	iconutil --convert icns --output $@ $(ICONSET_DIR)

.PHONY: app
app: build $(ICNS) ## Build the macOS .app bundle into ./build/GWiM.app
	@echo "==> Assembling $(APP_BUNDLE)"
	@rm -rf $(APP_BUNDLE)
	@mkdir -p $(APP_MACOS) $(APP_RES)
	@cp $(BUILD_DIR)/$(BINARY) $(APP_MACOS)/$(BINARY)
	@cp $(ICNS) $(APP_RES)/icon.icns
	@sed 's/__VERSION__/$(VERSION)/g' $(PLIST_TPL) > $(APP_CONTENTS)/Info.plist
	@touch $(APP_BUNDLE)
	@echo "    Bundle ready: $(APP_BUNDLE)"

.PHONY: install
install: app ## Copy GWiM.app to /Applications (overwriting existing install)
	@echo "==> Installing to /Applications"
	rm -rf /Applications/$(APP_NAME).app
	cp -R $(APP_BUNDLE) /Applications/

.PHONY: clean
clean: ## Remove build artifacts (binary, .app, generated icons)
	rm -rf $(BUILD_DIR)
	rm -rf $(ICONSET_DIR)
	rm -f internal/icon/assets/icon-active.png internal/icon/assets/icon-suspended.png

# ---------------------------------------------------------------------------
# Versioning
# ---------------------------------------------------------------------------

.PHONY: version
version: ## Print the current version
	@echo $(VERSION)

.PHONY: version-increment
version-increment: ## Bump PATCH (use BUMP=major|minor|patch to choose)
	@$(MAKE) --no-print-directory _bump BUMP=$${BUMP:-patch}

.PHONY: _bump
_bump:
	@awk -v bump=$(BUMP) -F'"' ' \
	  /const Version/ { \
	    n = split($$2, p, "."); \
	    if (bump=="major") { p[1]+=1; p[2]=0; p[3]=0 } \
	    else if (bump=="minor") { p[2]+=1; p[3]=0 } \
	    else { p[3]+=1 } \
	    new = p[1]"."p[2]"."p[3]; \
	    sub(/"[^"]+"/, "\""new"\""); \
	    print "==> Bumping " $$2 " -> " new > "/dev/stderr"; \
	  } \
	  { print } \
	' $(VERSION_FILE) > $(VERSION_FILE).tmp && mv $(VERSION_FILE).tmp $(VERSION_FILE)
	@gofmt -w $(VERSION_FILE)

# ---------------------------------------------------------------------------
# Release / publish
# ---------------------------------------------------------------------------
#
# `make push` is the ONLY sanctioned commit / publish path (per AGENTS.md).
# It refuses to run if CHANGELOG.md hasn't been updated since the last
# commit, enforcing the changelog-discipline rule from AGENTS.md.

.PHONY: push
push: check ## Bump patch, build, commit, push, tag — full release cycle
	@if git diff --quiet -- CHANGELOG.md && git diff --cached --quiet -- CHANGELOG.md; then \
	  echo "ERROR: CHANGELOG.md has not been updated. Add an entry before running 'make push'."; \
	  exit 1; \
	fi
	@$(MAKE) --no-print-directory version-increment
	@$(MAKE) --no-print-directory app
	@NEW_VERSION=$$(awk -F\" '/const Version/ {print $$2}' $(VERSION_FILE)); \
	 echo "==> Committing v$$NEW_VERSION"; \
	 git add -A; \
	 git commit -m "release: v$$NEW_VERSION"; \
	 git push; \
	 git tag "v$$NEW_VERSION"; \
	 git push origin "v$$NEW_VERSION"; \
	 echo "==> Released v$$NEW_VERSION"

# ---------------------------------------------------------------------------
# Convenience
# ---------------------------------------------------------------------------

.PHONY: deps
deps: ## Download / verify go module dependencies
	$(GO) mod download
	$(GO) mod verify
